name: Temporis CI

on:
  push:
    branches: [ "develop", "develop-testing-tofix", "sonar-testing", "main" ]
  pull_request:
    branches: [ "develop", "develop-testing-tofix", "sonar-testing-tofix", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Unit Tests & Generate Coverage Report
      env:
        ROBOLECTRIC_OFFLINE: "false"
      run: ./gradlew clean :app:testDebugUnitTest :app:testDebugUnitTestCoverageReport --no-daemon

    - name: Run SonarQube Scan Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # Ejecutamos la tarea contextualizada en el subproyecto para asegurar la indexación correcta
      run: ./gradlew :app:sonar --no-daemon --info
      
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: app/build/reports/jacoco/
